Data Grouping

**Q1. Problem Statement: Data Grouping - I**

Load the "big_bang_theory.csv" dataset into a DataFrame, group the data based on column "directed_by" using the groupby() function and the grouped DataFrame. Now also print all the episodes and the data associated with them, which belongs to the director - Mark Cendroski.

**Step-1:** Loading the dataset in a DataFrame.

In [ ]:
# importing pandas package
import pandas as pd
import numpy as np

# making data frame from csv file
df = pd.read_csv("/content/big_bang_theory_episodes.csv").fillna(np.nan)
display(df)

,season,episode_num_in_season,episode_num_overall,title,directed_by,written_by,original_air_date,prod_code,us_viewers
0,1,1,1,Pilot,James Burrows,Chuck Lorre & Bill Prady,2007-09-24,276023,9520000.0
1,1,2,2,The Big Bran Hypothesis,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-01,3T6601,8580000.0
2,1,3,3,The Fuzzy Boots Corollary,Mark Cendrowski,Story by: Chuck LorreTeleplay by: Bill Prady &...,2007-10-08,3T6602,8360000.0
3,1,4,4,The Luminous Fish Effect,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-15,3T6603,8150000.0
4,1,5,5,The Hamburger Postulate,Andrew D. Weyman,Story by: Jennifer GlickmanTeleplay by: Dave G...,2007-10-22,3T6604,8810000.0
...,...,...,...,...,...,...,...,...,...
274,12,20,275,The Decision Reverberation,Mark Cendrowski,Story by: Steven Molaro & Steve Holland & Tara...,2019-04-25,T12.16020,11840000.0
275,12,21,276,The Plagiarism Schism,Nikki Lorre,Story by: Eric Kaplan & Maria Ferrari & Adam F...,2019-05-02,T12.16021,12480000.0
276,12,22,277,The Maternal Conclusion,Kristy Cecil,Story by: Steve Holland & Eric Kaplan & Jeremy...,2019-05-09,T12.16022,12590000.0
277,12,23,278,The Change Constant,Mark Cendrowski,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16023,18520000.0
278,12,24,279,The Stockholm Syndrome,Mark Cendrowski,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16024,18520000.0

**Step-2:** Grouping the data based on director names.

In [ ]:
#Grouping data based on director names
result = df.groupby('directed_by')
display(result.first())

,season,episode_num_in_season,episode_num_overall,title,written_by,original_air_date,prod_code,us_viewers
directed_by,,,,,,,,
Andrew D. Weyman,1,5,5,The Hamburger Postulate,Story by: Jennifer GlickmanTeleplay by: Dave G...,2007-10-22,3T6604,8810000.0
Anthony Rich,3,20,60,The Spaghetti Catalyst,Chuck Lorre & Bill Prady & Lee Aronsohn & Stev...,2010-05-03,3X5570,11630000.0
Gay Linvill,7,16,151,The Table Polarization,Story by: Steven Molaro & Maria Ferrari & Tara...,2014-02-27,4x5316,17730000.0
Howard Murray,4,23,86,The Engagement Reaction,Story by: Bill Prady & Eric Kaplan & Jim Reyno...,2011-05-12,3X6673,10780000.0
James Burrows,1,1,1,Pilot,Chuck Lorre & Bill Prady,2007-09-24,276023,9520000.0
Joel Murray,1,9,9,The Cooper-Hofstadter Polarization,Story by: Bill Prady & Stephen EngelTeleplay b...,2008-03-17,3T6608,9110000.0
Kristy Cecil,12,9,264,The Citation Negation,Story by: Eric Kaplan & Tara Hernandez & Jerem...,2018-11-15,T12.16009,12560000.0
Mark Cendrowski,1,2,2,The Big Bran Hypothesis,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-01,3T6601,8580000.0
Nikki Lorre,9,7,190,The Spock Resonance,Story by: Chuck Lorre & Jim Reynolds & Tara He...,2015-11-05,4X7206,18810000.0
Peter Chakos,2,18,35,The Work Song Nanocluster,Story by: Bill Prady & Lee AronsohnTeleplay by...,2009-03-16,3T7368,9760000.0
Ted Wass,1,8,8,The Grasshopper Experiment,Story by: Dave Goetsch & Steven MolaroTeleplay...,2007-11-12,3T6607,9320000.0

**Step-3:** Printing the rows related to director- Mark Cendrowski

In [ ]:
#Printing individual groups
result.get_group('Mark Cendrowski')

,season,episode_num_in_season,episode_num_overall,title,written_by,original_air_date,prod_code,us_viewers
1,1,2,2,The Big Bran Hypothesis,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-01,3T6601,8580000.0
2,1,3,3,The Fuzzy Boots Corollary,Story by: Chuck LorreTeleplay by: Bill Prady &...,2007-10-08,3T6602,8360000.0
3,1,4,4,The Luminous Fish Effect,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-15,3T6603,8150000.0
5,1,6,6,The Middle Earth Paradigm,Story by: Dave GoetschTeleplay by: David Litt ...,2007-10-29,3T6605,8920000.0
6,1,7,7,The Dumpling Paradox,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-11-05,3T6606,9680000.0
...,...,...,...,...,...,...,...,...
272,12,18,273,The Laureate Accumulation,Story by: Steve Holland & Adam Faberman & Davi...,2019-04-04,T12.16018,12220000.0
273,12,19,274,The Inspiration Deprivation,Story by: Eric Kaplan & Maria Ferrari & Andy G...,2019-04-18,T12.16019,11440000.0
274,12,20,275,The Decision Reverberation,Story by: Steven Molaro & Steve Holland & Tara...,2019-04-25,T12.16020,11840000.0
277,12,23,278,The Change Constant,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16023,18520000.0
278,12,24,279,The Stockholm Syndrome,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16024,18520000.0

**Q2. Problem Statement: Data Grouping - II**

Load the "big_bang_theory.csv" dataset provided on LMS into a DataFrame; Group the data based on two columns, "directed_by" and "written_by," using the groupby() function and print the grouped DataFrame. Also, print the average viewers in the United States and the director and the writer's details.

**Step-1:** Loading the dataset in a DataFrame.

In [ ]:
# importing pandas package
import pandas as pd
import numpy as np

# making data frame from csv file
df = pd.read_csv("/content/big_bang_theory_episodes.csv")
display(df)

,season,episode_num_in_season,episode_num_overall,title,directed_by,written_by,original_air_date,prod_code,us_viewers
0,1,1,1,Pilot,James Burrows,Chuck Lorre & Bill Prady,2007-09-24,276023,9520000.0
1,1,2,2,The Big Bran Hypothesis,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-01,3T6601,8580000.0
2,1,3,3,The Fuzzy Boots Corollary,Mark Cendrowski,Story by: Chuck LorreTeleplay by: Bill Prady &...,2007-10-08,3T6602,8360000.0
3,1,4,4,The Luminous Fish Effect,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-15,3T6603,8150000.0
4,1,5,5,The Hamburger Postulate,Andrew D. Weyman,Story by: Jennifer GlickmanTeleplay by: Dave G...,2007-10-22,3T6604,8810000.0
...,...,...,...,...,...,...,...,...,...
274,12,20,275,The Decision Reverberation,Mark Cendrowski,Story by: Steven Molaro & Steve Holland & Tara...,2019-04-25,T12.16020,11840000.0
275,12,21,276,The Plagiarism Schism,Nikki Lorre,Story by: Eric Kaplan & Maria Ferrari & Adam F...,2019-05-02,T12.16021,12480000.0
276,12,22,277,The Maternal Conclusion,Kristy Cecil,Story by: Steve Holland & Eric Kaplan & Jeremy...,2019-05-09,T12.16022,12590000.0
277,12,23,278,The Change Constant,Mark Cendrowski,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16023,18520000.0
278,12,24,279,The Stockholm Syndrome,Mark Cendrowski,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16024,18520000.0

**Step-2:** Average US viewers of each writer and director.

In [ ]:
#Grouping data based on director and writer
result = df.groupby(['directed_by', 'written_by']) ['us_viewers'].mean()
result

directed_by       written_by
Andrew D. Weyman  Story by: Jennifer GlickmanTeleplay by: Dave Goetsch & Steven Molaro                                                  8810000.0
Anthony Rich      Chuck Lorre & Bill Prady & Lee Aronsohn & Steven Molaro                                                              11630000.0
                  Story by: Bill Prady & Eric Kaplan & Jim ReynoldsTeleplay by: Steven Molaro & Dave Goetsch & Steve Holland           17730000.0
                  Story by: Chuck Lorre & Bill Prady & Dave GoetschTeleplay by: Lee Aronsohn & Steven Molaro & Steve Holland           13630000.0
                  Story by: Chuck Lorre & Bill Prady & Steve HollandTeleplay by: Steven Molaro & Eric Kaplan & Anthony Del Broccolo    14020000.0
                                                                                                                                          ...
Peter Chakos      Story by: Chuck Lorre & Eric Kaplan & Adam FabermanTeleplay by: Steven Molaro & Steve Holland & Maria Ferrari        17250000.0
                  Story by: Chuck Lorre & Jim Reynolds & Jeremy HoweTeleplay by: Steven Molaro & Steve Holland & Eric Kaplan           14420000.0
                  Story by: Chuck Lorre & Lee Aronsohn & Steven MolaroTeleplay by: Bill Prady & Steve Holland & Maria Ferrari          15730000.0
                  Story by: Chuck Lorre & Steven Molaro & Maria FerrariTeleplay by: Bill Prady & Dave Goetsch & Jim Reynolds           11920000.0
Ted Wass          Story by: Dave Goetsch & Steven MolaroTeleplay by: Lee Aronsohn & Robert Cohen                                        9320000.0
Name: us_viewers, Length: 261, dtype: float64